# Generated by Django 5.2.6 on 2025-09-29 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('ml', 'ML/AI'), ('data', 'Data Science'), ('devops', 'DevOps'), ('design', 'UI/UX Design'), ('other', 'Other')], max_length=20)),
                ('resource_type', models.CharField(choices=[('tutorial', 'Tutorial'), ('video', 'Video'), ('slides', 'Slides'), ('code', 'Code Samples'), ('article', 'Article'), ('book', 'Book')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('Video', 'Video'), ('PPTX', 'PowerPoint'), ('ZIP', 'ZIP Archive'), ('Notebook', 'Jupyter Notebook'), ('Article', 'Web Article'), ('Other', 'Other')], max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('requires_membership', models.BooleanField(default=False)),
                ('downloads', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to='resources.resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='resources.resource')),
            ],
            options={
                'db_table': 'resource_tags',
                'unique_together': {('resource', 'tag')},
            },
        ),
    ]
